version: '3'
services:
  # Proxy
  proxy:
    container_name: proxy
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  # API
  api:
    build:
      dockerfile: api.dockerfile
      context: .
    volumes:
      - ./api:/app
    environment:
      VIRTUAL_HOST: api.test

  # MySQL Service
  db:
    image: mariadb:10.4-bionic
    restart: unless-stopped
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: api
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql

  # Redis
  redis:
    image: redis:latest
    restart: unless-stopped

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    restart: unless-stopped
    tty: true
    environment:
      VIRTUAL_HOST: phpmyadmin.test
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: secret
      PMA_ABSOLUTE_URI: http://phpmyadmin.test

# Volumes
volumes:
  dbdata:
    driver: local